#!/usr/bin/env python3
import os
import pandas as pd
import google.generativeai as genai
from tkinter import Tk, filedialog, messagebox, simpledialog, Label, Button, Text, END, Scrollbar, RIGHT, Y, LEFT, BOTH

"""
SANSCA AI Metadata Assistant
----------------------------
Workshop Tool: Demonstrating AI enrichment of digital asset metadata.
Usage: Load a CSV generated by DAMSG, enter an API key, and watch AI 
refine descriptions for museum-standard catalogs.
"""

def enrich_metadata(api_key, dataframe):
    # Configure the Gemini API
    genai.configure(api_key=api_key)
    # Using 'gemini-1.5-flash' for maximum compatibility across library versions
    # Using the stable 'gemini-1.5-flash' name to avoid 404 errors on different API versions
    model = genai.GenerativeModel('gemini-1.5-flash')
    
    summary_rows = []
    errors = []
    
    # Workshop safety: Skip metadata inventory rows and only process actual assets
    assets_only = dataframe[~dataframe.get('assetCategory', '').str.contains('metadata', case=False, na=False)]
    sample_size = min(len(assets_only), 10)
    
    for index, row in assets_only.head(sample_size).iterrows():
        # This is the 'Prompt' - participants can experiment with changing this text
        prompt = (
            f"You are a biodiversity informatics expert. Based on the following file metadata, "
            f"create a formal, archival-quality summary record for a museum catalog. "
            f"Institution: {row.get('institutionName', 'Unknown')}. "
            f"Collection: {row.get('collectionCode', 'Unknown')}. "
            f"File Name: {row.get('fileName', 'Unknown')}. "
            f"Raw Description: {row.get('description', 'No description available')}. "
            f"Return ONLY a single concise sentence summarizing the object depicted."
        )
        
        try:
            response = model.generate_content(prompt)
            # Create a new Summary Row based on the original asset
            new_row = row.copy()
            new_row['assetCategory'] = 'AI_SUMMARY'
            new_row['description'] = response.text.strip()
            new_row['title'] = f"Summary: {row.get('title', 'Unknown')}"
            summary_rows.append(new_row)
        except Exception as e:
            errors.append(f"File {row.get('fileName', 'Unknown')}: {str(e)}")
            
    return summary_rows, errors

class AIWorkshopApp:
    def __init__(self, root):
        self.root = root
        self.root.title("SANSCA AI Workshop Assistant")
        self.root.geometry("700x500")
        self.df = None
        self.enriched_df = None
        self.api_key = ""

        Label(root, text="SANSCA AI Enrichment Demo", font=("Arial", 14, "bold")).pack(pady=10)
        
        Label(root, text="Step 1: Load a generated Inventory CSV").pack()
        Button(root, text="Browse for CSV", command=self.load_csv, bg="lightgray").pack(pady=5)

        Label(root, text="Step 2: Authenticate").pack()
        Button(root, text="Enter Google AI API Key", command=self.get_key, bg="lightgray").pack(pady=5)

        Label(root, text="Step 3: Run Enrichment").pack()
        self.run_btn = Button(root, text="Enrich Sample (Top 10 Rows)", command=self.process, state="disabled", bg="lightblue")
        self.run_btn.pack(pady=10)

        self.save_btn = Button(root, text="Save Enriched CSV", command=self.save_csv, state="disabled", bg="lightgreen")
        self.save_btn.pack(pady=5)

        # Output display area
        self.frame = pd.DataFrame()
        self.output_area = Text(root, height=15, width=80, wrap="word")
        self.scrollbar = Scrollbar(root, command=self.output_area.yview)
        self.output_area.configure(yscrollcommand=self.scrollbar.set)
        
        self.scrollbar.pack(side=RIGHT, fill=Y)
        self.output_area.pack(side=LEFT, fill=BOTH, padx=10, pady=10)

    def load_csv(self):
        path = filedialog.askopenfilename(filetypes=[("CSV files", "*.csv")])
        if path:
            try:
                self.df = pd.read_csv(path)
                messagebox.showinfo("Success", f"Loaded {len(self.df)} records from {os.path.basename(path)}")
                self.check_ready()
            except Exception as e:
                messagebox.showerror("Error", f"Failed to read CSV: {e}")

    def get_key(self):
        key = simpledialog.askstring("API Key", "Enter your Gemini API Key:", show='*')
        if key:
            self.api_key = key
            self.check_ready()

    def check_ready(self):
        if self.df is not None and self.api_key:
            self.run_btn.config(state="normal")

    def process(self):
        if "description" not in self.df.columns:
            messagebox.showerror("Column Error", "The CSV must have a 'description' column.")
            return

        if not self.api_key:
            messagebox.showerror("API Key Error", "Please enter your Google AI API Key.")
            return

        self.output_area.delete(1.0, END)
        self.output_area.insert(END, "Connecting to AI... processing metadata samples...\n\n")
        self.root.update()
        
        # Filter for the UI display as well
        assets_only = self.df[~self.df.get('assetCategory', '').str.contains('metadata', case=False, na=False)]
        new_summary_rows, errors = enrich_metadata(self.api_key, assets_only)
        
        if errors:
            self.output_area.insert(END, "CONNECTION OR API ISSUES DETECTED:\n")
            for err in errors:
                self.output_area.insert(END, f"- {err}\n")
            self.output_area.insert(END, "\n" + "="*40 + "\n\n")

        if new_summary_rows:
            # Create a dataframe of the summaries and append to the original
            summary_df = pd.DataFrame(new_summary_rows)
            self.enriched_df = pd.concat([self.df, summary_df], ignore_index=True)
            
            for row in new_summary_rows:
                self.output_area.insert(END, f"NEW SUMMARY ROW CREATED:\n")
                self.output_area.insert(END, f"ASSET: {row['fileName']}\n")
                self.output_area.insert(END, f"SUMMARY: {row['description']}\n")
                self.output_area.insert(END, "-"*40 + "\n")
                self.root.update()
            
            self.save_btn.config(state="normal")
            messagebox.showinfo("Complete", f"Generated {len(new_summary_rows)} new summary rows.")

    def save_csv(self):
        if self.enriched_df is not None:
            save_path = filedialog.asksaveasfilename(defaultextension=".csv", filetypes=[("CSV files", "*.csv")])
            if save_path:
                self.enriched_df.to_csv(save_path, index=False)
                messagebox.showinfo("Saved", f"Enriched CSV saved to: {save_path}")

if __name__ == "__main__":
    root = Tk()
    app = AIWorkshopApp(root)
    root.mainloop()